### ISSUE TITLE
Support Linux

### ISSUE THREAD

**Issue by skylord123** [brianmiller/phvalheim-client#2]
Would love Linux support. I do a lot of playing on my Steam Deck or Linux laptop and would like to be able to run this client. 

Thanks for the great software!

**Comment by brianmiller** [comment]
Linux is certainly coming. 👍

**Comment by brianmiller** [comment]
An early update,

We have a Linux client working pretty well--a huge thank you to @solaris765 for the merge https://github.com/brianmiller/phvalheim-client/commit/5751f40595f636f5111519c4c8a09704f7dc0cba. We have beta universal and .deb packages available in the [linux](https://github.com/brianmiller/phvalheim-client/tree/master/published_build/linux) directory.  Builds will be moving around into a more multi-OS friendly approach. Stay tuned for official builds...

**Comment by brianmiller** [comment]
Native Linux support has been released, closing.

**Comment by skylord123** [comment]
> Native Linux support has been released, closing.

Nice! Just got around to trying it out and it's working great. Thanks for getting this added.
